version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

root:
  level: INFO
  handlers: [console, file]

handlers:
  console:
    class : logging.StreamHandler
    formatter: simple
    level   : INFO
    stream  : ext://sys.stdout

  file:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs.log
    maxBytes: 1024 * 512
    backupCount: 3
